Small layout and style issues
phivk/tolerant-futures pull request #159
Opened 2022-05-29 20:59 UTC by Solcany

2022-05-29 22:20 UTC, phivk requested changes
really great improvements to the look and feel, these make it feel a lot more whole ❤️ 

besides my inline comments, please see:

CardItem get's displayed under spectrum:
![Screen Shot 2022-05-30 at 00 10 44](https://user-images.githubusercontent.com/902958/170893275-df3e5d71-6c6a-4241-a1ef-44b3603fef42.png)

Buttons should have `cursor: pointer` to signal they are clickable:
<img width="173" alt="Screenshot 2022-05-30 at 00 14 59" src="https://user-images.githubusercontent.com/902958/170893385-0bcb0f17-e1da-441a-9561-6822503341c4.png">

2022-05-29 22:20 UTC, phivk commented on components/TheExitConfirmation.vue
> +  <div v-show="isIdle" class="confirm-exit-container">
what is `v-show="isIdle"` doing here?

2022-05-29 22:20 UTC, phivk commented on plugins/idle-vue.js
> +  idleTime: 300000,
idleTime should be 60000 == 60 seconds

2022-05-29 22:56 UTC, Solcany commented
@phivk 

> CardItem get's displayed under spectrum:

CardItem displays correctly on my end, but i increased z index of the draggable so please try again


> Buttons should have `cursor: pointer` to signal they are clickable:

They do have and display pointer on hover on my end

2022-05-30 06:17 UTC, phivk approved these changes

2022-05-30 06:28 UTC, merged